### ISSUE TITLE
Version 0.20.0 can not be build with usrsctp 0.9.5.0

### ISSUE THREAD

**Issue by tytan652** [paullouisageneau/libdatachannel#1100]
On Linux distros, submodules are avoided and mostly only stable release of dependencies are used.
But libdatachannel 0.20.0 seems to use non-released usrsctp APIs, which make it not build-able on Linux.

```
build/libdatachannel-nice/src/libdatachannel/src/impl/sctptransport.cpp: In constructor ‘rtc::impl::SctpTransport::SctpTransport(std::shared_ptr<rtc::impl::Transport>, const rtc::Configuration&, Ports, rtc::message_callback, amount_callback, rtc::impl::Transport::state_callback)’:
/build/libdatachannel-nice/src/libdatachannel/src/impl/sctptransport.cpp:273:21: error: ‘SCTP_EDMID_LOWER_LAYER_DTLS’ was not declared in this scope
  273 |         int edmid = SCTP_EDMID_LOWER_LAYER_DTLS;
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 70%] Building CXX object CMakeFiles/datachannel.dir/src/impl/utils.cpp.o
/build/libdatachannel-nice/src/libdatachannel/src/impl/sctptransport.cpp:274:53: error: ‘SCTP_ACCEPT_ZERO_CHECKSUM’ was not declared in this scope
  274 |         if (usrsctp_setsockopt(mSock, IPPROTO_SCTP, SCTP_ACCEPT_ZERO_CHECKSUM, &edmid, sizeof(edmid)))
      |                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/datachannel.dir/build.make:552: CMakeFiles/datachannel.dir/src/impl/sctptransport.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:84: CMakeFiles/datachannel.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by paullouisageneau** [comment]
It is fixed by https://github.com/paullouisageneau/libdatachannel/pull/1099, I released the fix as `v0.20.1`.

Since the last tagged version of usrsctp is 3 years old now, various enhancements are not included, that's why the submodule is way more recent and I didn't test linking against usrsctp 0.9.5.0.
