### ISSUE TITLE
Unable to build. Please help.

### ISSUE THREAD

**Issue by AMajor-C** [paullouisageneau/libdatachannel#1398]
Windows. MinGW 8.x
cmake -B build -S . -G "MinGW Makefiles" -DCMAKE_INSTALL_PREFIX=./
cmake --build build --config Release

```
[ 36%] Building CXX object CMakeFiles/datachannel.dir/src/dependencydescriptor.cpp.obj
In file included from D:\Projects\Qt\NextTalk\libdatachannel\src\dependencydescriptor.cpp:9:0:
D:/Projects/Qt/NextTalk/libdatachannel/include/rtc/dependencydescriptor.hpp:21:32: error: 'std::byte' has not been declared
  static BitWriter fromSizeBits(std::byte *buf, size_t offsetBits, size_t sizeBits);
                                ^~~
D:/Projects/Qt/NextTalk/libdatachannel/include/rtc/dependencydescriptor.hpp:35:7: error: 'byte' in namespace 'std' does not name a type
  std::byte *mBuf = nullptr;
       ^~~~
D:/Projects/Qt/NextTalk/libdatachannel/include/rtc/dependencydescriptor.hpp:94:15: error: 'std::byte' has not been declared
  void writeTo(std::byte *buf, size_t sizeBytes) const;
               ^~~
D:\Projects\Qt\NextTalk\libdatachannel\src\dependencydescriptor.cpp:18:40: error: 'rtc::BitWriter rtc::BitWriter::fromSizeBits' is not a static data member of 'struct rtc::BitWriter'
 BitWriter BitWriter::fromSizeBits(std::byte *buf, size_t offsetBits, size_t sizeBits) {
                                        ^~~~
D:\Projects\Qt\NextTalk\libdatachannel\src\dependencydescriptor.cpp:18:40: error: 'byte' is not a member of 'std'
D:\Projects\Qt\NextTalk\libdatachannel\src\dependencydescriptor.cpp:18:46: error: 'buf' was not declared in this scope
 BitWriter BitWriter::fromSizeBits(std::byte *buf, size_t offsetBits, size_t sizeBits) {
                                              ^~~
D:\Projects\Qt\NextTalk\libdatachannel\src\dependencydescriptor.cpp:18:58: error: expected primary-expression before 'offsetBits'
 BitWriter BitWriter::fromSizeBits(std::byte *buf, size_t offsetBits, size_t sizeBits) {
                                                          ^~~~~~~~~~
D:\Projects\Qt\NextTalk\libdatachannel\src\dependencydescriptor.cpp:18:77: error: expected primary-expression before 'sizeBits'
 BitWriter BitWriter::fromSizeBits(std::byte *buf, size_t offsetBits, size_t sizeBits) {
                                                                             ^~~~~~~~
D:\Projects\Qt\NextTalk\libdatachannel\src\dependencydescriptor.cpp:18:87: error: expected ',' or ';' before '{' token
 BitWriter BitWriter::fromSizeBits(std::byte *buf, size_t offsetBits, size_t sizeBits) {
                                                                                       ^
D:\Projects\Qt\NextTalk\libdatachannel\src\dependencydescriptor.cpp: In member function 'bool rtc::BitWriter::write(uint64_t, size_t)':
D:\Projects\Qt\NextTalk\libdatachannel\src\dependencydescriptor.cpp:38:15: error: 'mBuf' was not declared in this scope
  uint8_t *p = mBuf == nullptr ? nullptr : reinterpret_cast<uint8_t *>(mBuf + mOffset / 8);
               ^~~~
D:\Projects\Qt\NextTalk\libdatachannel\src\dependencydescriptor.cpp: At global scope:
D:\Projects\Qt\NextTalk\libdatachannel\src\dependencydescriptor.cpp:220:47: error: variable or field 'writeTo' declared void
 void DependencyDescriptorWriter::writeTo(std::byte *buf, size_t sizeBytes) const {
                                               ^~~~
D:\Projects\Qt\NextTalk\libdatachannel\src\dependencydescriptor.cpp:220:47: error: 'byte' is not a member of 'std'
D:\Projects\Qt\NextTalk\libdatachannel\src\dependencydescriptor.cpp:220:53: error: 'buf' was not declared in this scope
 void DependencyDescriptorWriter::writeTo(std::byte *buf, size_t sizeBytes) const {
                                                     ^~~
D:\Projects\Qt\NextTalk\libdatachannel\src\dependencydescriptor.cpp:220:65: error: expected primary-expression before 'sizeBytes'
 void DependencyDescriptorWriter::writeTo(std::byte *buf, size_t sizeBytes) const {
                                                                 ^~~~~~~~~
mingw32-make.exe[2]: *** [CMakeFiles\datachannel.dir\build.make:136: CMakeFiles/datachannel.dir/src/dependencydescriptor.cpp.obj] Error 1
```

**Comment by paullouisageneau** [comment]
This looks like an issue introduced by https://github.com/paullouisageneau/libdatachannel/pull/1127, it should be fixed with https://github.com/paullouisageneau/libdatachannel/pull/1400.

**Comment by AMajor-C** [comment]
> This looks like an issue introduced by [#1127](https://github.com/paullouisageneau/libdatachannel/pull/1127), it should be fixed with [#1400](https://github.com/paullouisageneau/libdatachannel/pull/1400).

Thank you very much.
Now there is anoter issue with building:
```
[ 47%] Building CXX object CMakeFiles/datachannel.dir/src/h264rtppacketizer.cpp.obj
D:/Projects/Qt/libdatachannel/include/rtc/common.hpp:17:24: error: expected identifier before '__attribute__'
 #define RTC_CPP_EXPORT __declspec(dllexport) // building the library
                        ^
D:/Projects/Qt/libdatachannel/include/rtc/nalunit.hpp:185:22: note: in expansion of macro 'RTC_CPP_EXPORT'
 class [[deprecated]] RTC_CPP_EXPORT NalUnits : public std::vector<shared_ptr<NalUnit>> {
                      ^~~~~~~~~~~~~~
In file included from D:/Projects/Qt/libdatachannel/include/rtc/h264rtppacketizer.hpp:15:0,
                 from D:\Projects\Qt\libdatachannel\src\h264rtppacketizer.cpp:11:
D:/Projects/Qt/libdatachannel/include/rtc/nalunit.hpp:185:46: error: expected initializer before ':' token
 class [[deprecated]] RTC_CPP_EXPORT NalUnits : public std::vector<shared_ptr<NalUnit>> {
                                              ^
mingw32-make.exe[2]: *** [CMakeFiles\datachannel.dir\build.make:361: CMakeFiles/datachannel.dir/src/h264rtppacketizer.cpp.obj] Error 1
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:350: CMakeFiles/datachannel.dir/all] Error 2
mingw32-make.exe: *** [Makefile:135: all] Error 2
```

**Comment by paullouisageneau** [comment]
The variable is inline so it shouldn't even try to link it. Try rebuilding from a clean project.

**Comment by AMajor-C** [comment]
> The variable is inline so it shouldn't even try to link it. Try rebuilding from a clean project.

I did purge all changes and rebooted OS and it helped but now i get some troubles with linking opessl:

```
[ 73%] Linking CXX shared library libdatachannel.dll
C:/Qt/Tools/mingw1310_64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\datachannel.dir/objects.a(certificate.cpp.obj):certificate.cp:(.text+0x273): undefined reference to `BIO_s_mem'
```
also i tried to use openssl 3.1.2 with same result

**Comment by AMajor-C** [comment]
> > Im bulding x86 version so openssl is also x86 i use versions which distributed with Qt. So libdatachannel requires x64 only ?
> 
> Given the output you posted, you are building libdatachannel for x64 (the toolchain is x86_64-w64-mingw32). Libdatachannel does not require a particular architecture.

I DID IT! Idk how i just went dumb way and simple put the project to qt-creator and it helped. I guess IDE reconfigured some things in cmake project...

![Image](https://github.com/user-attachments/assets/7d1f2c6b-8d09-4999-b6d6-540b60b10412)
